# Generated by Django 6.0.5 on 2026-05-07 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='上架状态'),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, verbose_name='低库存阈值'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='库存'),
        ),
        migrations.CreateModel(
            name='RestockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='补货数量')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='补货时间')),
                ('operator', models.CharField(blank=True, default='', max_length=100, verbose_name='操作人')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restock_records', to='recognition.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '补货记录',
                'verbose_name_plural': '补货记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
